### ISSUE TITLE
Notifications & Sounds

### ISSUE THREAD

**Issue by RobijnGit** [HumanTree92/esx_panicbutton#2]
As the title says, Notifications & Sounds as soon as you press the panic button. This then automatically sets a route (not a waypoint, but a route as you would get it at the delivery job)

**Comment by HumanTree92** [comment]
You can add these yourself. As i have stated i will no longer be providing support for this script. And prefer people to follow https://github.com/HumanTree92/esx_panicbutton/wiki/Better-ESX-Panic-Button
